import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Pirata_One } from 'next/font/google'

const pirataOne = Pirata_One({ 
  weight: '400', 
  subsets: ['latin'], 
  variable: '--font-unifraktur' 
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${pirataOne.variable} dark`}>
      <body className="bg-black text-white antialiased">
        {children}
      </body>
    </html>
  );
}
